project setup
PawelM17/resource-manager-app pull request #1
Opened 2022-10-03 14:03 UTC by PawelM17

- create initial project structure,
- configure database connection,

2022-10-03 16:57 UTC, karolk92 requested changes
garsc przydatnych informacji na poczatek :)

2022-10-03 16:57 UTC, karolk92 commented on pom.xml
> +            <groupId>javax.xml.bind</groupId>
do czego potrzebujesz tej zaleznosci?

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +    public void saveResource (@RequestBody ResourceEntity resourceEntity){
przerob takie miejsca jak to zeby wartstwa perzystencji (encja) nie przenikala do frontu, unika sie takiego podejscia, podaj tu np. ResourceRequest ktory bedzie zawieral takie same pola jak encja a nastepnie przemapuj builderem (builder pattern) na obiekt bazodanowy (encja)

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +    public void deleteResource (@RequestBody ResourceEntity resourceEntity){
1. usuwanie powinno odbywac sie poprzed podanie ID obiektu do usuniecia, a nie calego obiektu
2. nie powinienes tworzyc sciezki urla (patha) jesli jest to usuwanie, tworzenie, edycja, odczyt - eng. CRUD (create, read, update, delete), od tego masz metody ktore Ci to charakteryzuja (POST, GET, PUT, DELETE)

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +    public void saveResource (@RequestBody ResourceEntity resourceEntity){
1. moznaby tu zwrocic id zapisanego obiektu, aby front mogl wykonywac operacja przy uzyciu identyfikatora zasobu
2. nie powinienes tworzyc sciezki urla (patha) jesli jest to usuwanie, tworzenie, edycja, odczyt - eng. CRUD (create, read, update, delete), od tego masz metody ktore Ci to charakteryzuja (POST, GET, PUT, DELETE)

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/UserController.java
> +        userService.saveUser(userEntity);
zwroc id usera (zeby front mogl przy jego uzyciu robic operacje tj. usuwanie, edycja, odczyt)

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/UserController.java
> +    public void deleteUser (@RequestBody UserEntity userEntity){
tak jak przy resource /delete zbedne, metoda HTTP mowi ci ze to delete

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/UserController.java
> +    public void updateUserNickName(@RequestBody UserEntity userEntity){
jw. /update zbedne, jesli aktualizujesz konkretna rzecz (nick) to wystarczy ze tylko to pole podasz jako body, nie podawaj calego obiektu jesli aktualizujesz jedno pole

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/persistance/ResourceRepository.java
> +public interface ResourceRepository extends JpaRepository<ResourceEntity, Long> {
fyi - jesli rozszerzasz JpaRepository to taka klasa automatycznie jest czytana przez kontekst springa i @Repository nie jest niezbedne, mimo to fajnie jest to zostawic dla przejrzystosci kodu

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/persistance/UserRepository.java
> +    @Query(value = "UPDATE UserEntity SET nickName = :nickName WHERE userId = :userId")
@Transactional w tym miejscu zbedne - metoda albo sie wykona albo nie, doczytaj o tej adnotacji

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/ResourceService.java
> +    public void saveResource(ResourceEntity resourceEntity) {
przerob to tak aby nie przekazywac z frontu ResourceEntity tylko np. ResourceRequest ktory nastepnie przemapujesz na ResourceEntity (przez builder)

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/UserService.java
> +        userRepository.save(new UserEntity(user.getUserId(), user.getNickName(), user.getName(), user.getLastName()));
tutaj balagan - teoretycznie moglbys po prostu przekazac encje usera z frontu, ale przerob tak jak pisalem wyzej

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/UserService.java
> +    public void deleteUser (UserEntity user){
odstepy pomiedzy metodami!

2022-10-03 16:57 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/persistance/UserRepository.java
> +    @Modifying
nie jestem pewien czy tej adnotacji (@Modyfing) uzywa sie w taki sposob, sprawdz

2022-10-03 17:58 UTC, maciejDun commented on src/main/java/pl/gispartner/ResourceManagerApp/service/UserService.java
> +        userRepository.updateUserNickName(userId, newUserNickName);
A może tu podać cała encje z frontu

2022-10-03 18:06 UTC, maciejDun commented on src/main/java/pl/gispartner/ResourceManagerApp/model/UserEntity.java
> +    private String name;
firstName dla porządku?

2022-10-03 18:06 UTC, maciejDun commented on src/main/java/pl/gispartner/ResourceManagerApp/model/ResourceEntity.java
> +//    private String resourceType; TODO
Komentarzy nie wrzucamy w pr, na przyszłość może bardziej

2022-10-05 09:10 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/UserService.java
> +        userRepository.updateUserNickName(userId, newUserNickName);
encja nie powinna byc widoczna dla frontu

2022-10-06 10:32 UTC, karolk92 requested changes

2022-10-06 10:32 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/ResourceDto.java
> +    private Long resourceId;
zostaw po prostu id, jest w obiekcie resourceDto wiec to samo przez sie mowi ze to jest id resourca

2022-10-06 10:32 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/ResourceEntity.java
>      @Id
resourceId  zmien na id - skoro jest w resource to wiadomo ze to id zasobu

2022-10-06 10:32 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/ResourceMapper.java
> +    public ResourceEntity mapToEntity(ResourceDto resourceDto) {
metoda powinna byc statyczna, nic nie modyfikuje, wykonuje tylko operacje. Dzieki temu bedziesz mogl sie do niej odwolac poprzez ResourceMapper.mapToEntity

2022-10-06 10:32 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/ResourceMapper.java
> +@Component
nie ma potrzeby zeby mapper byl beanem

2022-10-06 10:32 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/UserDto.java
> +    private Long userId;
userId >id

2022-10-06 10:32 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/UserMapper.java
> +@Component
to nie powinien byc component

2022-10-06 10:32 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/UserMapper.java
> +    public UserEntity mapToEntity(UserDto userDto) {
metoda statyczna

2022-10-11 11:51 UTC, karolk92 requested changes
ogolnie rzecz biorac widac duze postepy, jestem zadowolony :)

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +    @PutMapping("/name/{resourceId}")
w tej sytuacji jak zlozysz sobie urla to bedziesz mial /api/resource/name/{id} a to nie jest id imienia tylko zasobu. Zamien na /api/resource/{id}/name - w pozostalych miejscach zrob analogicznie tj. dla usera i w polach dla name i jsonData

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +    @PutMapping("/data/{resourceId}")
jw

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +    @PutMapping("/name/{resourceId}")
przekazalbym tez usera tutaj w jakis sposob i dodal walidacje czy user jest ownerem. Unikniesz sytuacji kiedy inny uzytkownik zmodyfikuje twoj zasob

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +    @PutMapping("/data/{resourceId}")
tutaj tez przekaz usera i zwaliduj

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/AuditableBase.java
> +public class AuditableBase {
bardzo ladnie ze wydzielone

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/ResourceMapper.java
> +        ObjectMapper objectMapper = new ObjectMapper();
objectMapper zrob jako beana ktorego tylko wstrzykniesz do tego ResourceMappera. Zrob sobie katalog /configuration i tam zdefiniuj Beana. ResourceMappera oczywiscie przerob tak aby byl komponentem springowym

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/ResourceService.java
> +        ResourceEntity created = resourceRepository.save(resourceEntity);
jakis enter/pusta linia dla czytelnosci

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/ResourceService.java
> +        resourceEntity.setModifiedDate(new Date());
mozesz tez uzyc LocalDate.now()

2022-10-11 11:51 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/UserService.java
> +        userRepository.deleteById(userId);
te walidacje o ktorym pisalem (czy odpowiedni uzytkownik najlepiej zrobic w serwisie), tutaj np. moglbys zwalidowac ze jesli usuwasz siebie to nie ma problemu, a zeby usunac innego uzytkownika to musisz byc SUPER_USER

2022-10-13 20:33 UTC, karolk92 approved these changes
elegancko, etap 1 za nami! :)

2022-10-13 20:33 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +        if (resourceService.validateResourceOwner(userId, resourceId)) {
przetlumacz sobie to zdanie - "jesli zwaliduj wlasciciela zasobu", brzmi kiepsko, nie? jesli uzywasz w ifie to nazwe metody trzeba zmienic na np. `isResourceOwnerValid` wiedy w ifie bedzie `if (isResourceOwnerValid(userId, resourceId)` czyli "jesli jest poprawny wlasciciel zasobu to zrob to".
Tego pierwszego wariantu moglbys uzyc gdybys nic nie zwracal z ifa, a wewnatrz metody rzucal wyjatek.

2022-10-13 20:33 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/api/ResourceController.java
> +        if (resourceService.validateResourceOwner(userId, resourceId)) {
jak dla mnie - najlepiej byloby tak: (jesli juz nie chcesz tego do serwisu przenosic - bo to bylaby jeszcze lepsza opcja)
`        if (!resourceService.isResourceOwnerValid(userId, resourceId)) {
               return "This operation cannot be performed";  
        }
          resourceService.deleteResource(resourceId);  
          return "Changes have been successfully saved";`

2022-10-13 20:33 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/model/ResourceEntity.java
> +    @Override
lombok ma adnotacje od eq and hash

2022-10-13 20:33 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/ResourceService.java
> +        ResourceEntity resourceEntity = resourceRepository.getReferenceById(resourceId);
na przyszlosc z tym`getReferenceById` raczej uzywaj `findById`, nigdy w kodzie nie widzialem zeby ktos tego uzyl wiec lepiej uzywac tego co wiekszosc. Nie mowie ze to podejscie jest trafne w kazdym przypadku ale wtedy na pewno twoj kod bedzie czytelniejszy dla innych

2022-10-13 20:33 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/ResourceService.java
> +        return Objects.equals(userId, resourceEntity.getUser().getId()) || userEntity.getUserType().equals(SUPER_USER);
raz uzywasz Objects.equals a raz equals, badz konsekwentny i uzyj jednej opcji

2022-10-13 20:33 UTC, karolk92 commented on src/main/java/pl/gispartner/ResourceManagerApp/service/UserService.java
> +        return Objects.equals(id, userId) || userEntity.getUserType().equals(SUPER_USER);
jw

2022-10-13 20:36 UTC, merged